<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhA9uwm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhA9uwm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOhA9uwm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOhA9uwm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOhA9uwm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OhA9uwm',
    'container.build_id' => '0b9dac6f',
    'container.build_time' => 1564140137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhA9uwm');
