<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4faAexN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4faAexN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4faAexN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4faAexN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4faAexN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4faAexN',
    'container.build_id' => '358002bc',
    'container.build_time' => 1563957281,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4faAexN');
